services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://192.168.29.2:11434
    volumes:
      - ./data:/app/backend/data
    restart: unless-stopped

