services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://192.168.29.2:11434
    volumes:
      - ./data:/app/backend/data
    restart: unless-stopped
    labels:
      glance.name: Open-WebUI
      glance.icon: sh:open-webui
      glance.url: http://rpi.netbird.cloud:3000
      glance.description: Frontend for Ollama
      glance.id: open-webui
      glance.category: general