services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    env_file: .env
    networks:
      - exposed_internet

networks:
  exposed_internet:
    external: true
