services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      # Optionally, also mount docker socket if you want to use the docker containers widget
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/hdd:/mnt/hdd:ro  # check filled stats
      - /mnt/ssd:/mnt/ssd:ro  # check filled stats
    ports:
      - 8082:8080
    env_file: .env
    depends_on:
      - ytrec
    labels:
      # glance.hide: true
      glance.name: Glance
      glance.icon: si:docker
      glance.url: http://192.168.29.2:8082
      glance.description: Dashboard for homelab
      glance.id: glance

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    labels:
      glance.parent: glance
      glance.name: Ollama
      glance.icon: si:ollama

  ytrec:
    container_name: ytrec
    build:
      context: ./ytrec
    restart: unless-stopped
    volumes:
      - ./ytrec:/app
    ports:
      - "5500:5500"
    depends_on:
      - ollama
    labels:
      glance.parent: glance
      glance.name: YT Recommender
      glance.icon: si:docker