services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/hdd:/mnt/hdd:ro
      - /mnt/ssd:/mnt/ssd:ro
    ports:
      - 8082:8080
    env_file: .env
    depends_on:
      - ollama-rss
    labels:
      glance.name: Glance
      glance.icon: di:glance
      glance.url: http://192.168.29.2:8082
      glance.description: Dashboard for homelab
      glance.id: glance
      glance.category: general

  ollama-rss:
    container_name: ollama-rss
    build:
      context: ./tools/ollama-rss-rust
    restart: unless-stopped
    ports:
      - "5500:5500"
    labels:
      glance.parent: glance
      glance.name: Ollama RSS (Rust)
      glance.icon: si:rust
      glance.category: general

  # ollama-rss:
  #   container_name: ollama-rss
  #   build:
  #     context: ./tools/ollama-rss-go
  #   restart: unless-stopped
  #   ports:
  #     - "5500:5500"
  #   labels:
  #     glance.parent: glance
  #     glance.name: Ollama RSS (Go)
  #     glance.icon: si:go
  #     glance.category: general

  # watcher:
  #   container_name: watcher
  #   build:
  #     context: ./watcher
  #   restart: unless-stopped
  #   volumes:
  #     - ./watcher:/app
  #   network_mode: host
  #   labels:
  #     glance.parent: glance
  #     glance.name: Watches system stats
  #     glance.icon: si:docker
  #     glance.category: general
